# example values
server:
  port: 8080
  error:
      include-message: always
spring:
#  banner:
#    charset: UTF-8
#    location:
#    classpath: banner.txt

  datasource:
    username: root
    password: password
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 30
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  output:
      ansi:
        enabled: always

  jpa:
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
#        generate_statistics: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
#        enable_lazy_load_no_trans: true
#        event:
#          merge:
#            entity_copy_observer: allow
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true
      useUnicode: true
      characterEncoding: utf-8
      dialect: org.hibernate.dialect.MySQL8Dialect
jsoup-setting:
  jsoup:
    userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0
    referrer: http://www.google.com
    timeout: 5_000
    ignoreHttpErrors: true
    followRedirects: false

indexing-settings:
  sites:
#    - url: https://habr.com/
#      name: habr
#    - url: http://www.playback.ru/
#      name: playback
#    - url: https://www.artlebedev.ru/
#      name: artlebedev.ru
    - url: https://www.svetlovka.ru/
      name: Svetlovka
    - url: https://dombulgakova.ru/
      name: Дом Булгакова
#    - url: https://www.tretyakovgallery.ru/
#      name: Третьяковская галерея
    - url: https://gallery.tverreg.ru/
      name: Тверская Картинная галерея
    - url: https://shm.ru/
      name: Исторический музей
#    - url: https://www.artlebedev.ru/technogrette/
#      name: Студия Лебедева. Техногрет
#    - url: https://www.artlebedev.ru/kovodstvo/sections/
#      name: Студия Лебедева. Ководство
    - url: https://nopaper.ru/
      name: Нет Бумаге!
    - url: https://mydiscoveries.ru/
      name: Новые открытия каждый день
    - url: https://opisanie-kartin.com/
      name: Описание картин

table-settings:
  clear-site-if-not-exists: true
  delete-next-level-pages: true
