# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  output:
      ansi:
        enabled: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true
jsoup-setting:
  jsoup:
    userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0
    referrer: http://www:google:com"
    timeout: 10000
    ignoreHttpErrors: true
    followRedirects: false

indexing-settings:
  sites:
#    - url: http://www.tema.ru
#      name: Артемий Лебедев
    - url: http://twitter.com
      name: TWITTER
    - url: http://slenta.ru/
      name: sLenta
    - url: http://www.bbc.com
      name: BBC.com
#    - url: https://www.rambler.ru
#      name: Rambler.Ru
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru


