# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  output:
      ansi:
        enabled: always

  jpa:
    properties:
      hibernate:
#        enable_lazy_load_no_trans: true
#        event:
#          merge:
#            entity_copy_observer: allow
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true
      useUnicode: true
      characterEncoding: utf-8
jsoup-setting:
  jsoup:
    userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0
    referrer: http://www:google.com
    timeout: 5_000
    ignoreHttpErrors: true
    followRedirects: false

indexing-settings:
  sites:
#    - url: https://www.artlebedev.ru/
#      name: ArtLebedev
#    - url: https://lenta.ru/
#      name: Lenta
#    - url: https://volochek.life/
#      name: Volochek_very_big_string_apporx_3r_links
#    - url: https://www.playback.ru/
#      name: PlayBack.Ru
    - url: http://radiomv.ru/
      name: Радио MV 13
#    - url: https://ipfran.ru/
#      name: ИПФ РАН 1042
#    - url: www.bbc.com
#      name: BBC.com
    - url: https://nikoartgallery.com/
      name: Niko Art 91
    - url: https://et-cetera.ru/mobile/
      name: Et Cet-era 52
#    - url: https://www.lutherancathedral.ru/
#      name: Lutheran cathedral 842
#    - url: https://dombulgakova.ru/
#      name: Дом Булгакова 529
    - url: https://www.svetlovka.ru/
      name: Светловка 231
    - url: http://cimus.biz/
      name: Cimus 19
#    - url: https://xakep.ru/
#      name: xakep
#    - url: https://niasvizh.by/
#      name: Несвиж
#    - url: https://habr.com/ru/hub/java/
#      name: JAVA_Hub Habr



