# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  output:
      ansi:
        enabled: always

  jpa:
    properties:
      hibernate:
#        enable_lazy_load_no_trans: true
#        event:
#          merge:
#            entity_copy_observer: allow
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: create
      show-sql: true
      format_sql: true
      use_sql_comments: true
      useUnicode: true
      characterEncoding: utf-8
jsoup-setting:
  jsoup:
    userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0
    referrer: http://www:google.com
    timeout: 1_000
    ignoreHttpErrors: true
    followRedirects: false

indexing-settings:
  sites:
#    - url: http://www.artlebedev.ru/
#      name: ArtLebedev
#    - url: https://lenta.ru/
#      name: Lenta
#    - url: https://volochek.life/
#      name: Volochek_very_big_string_apporx_3r_links
#    - url: https://www.playback.ru/
#      name: PlayBack.Ru
#    - url: http://radiomv.ru/
#      name: Радио_MV_13_pages
#    - url: https://ipfran.ru/
#      name: IP_fran_1042_pages
#    - url: www.bbc.com
#      name: BBC.com
#    - url: https://nikoartgallery.com/
#      name: Niko_Art_Gallery_91_pages
#    - url: https://et-cetera.ru/mobile/
#      name: Et_Cetera_4_mobile_52_pages
#    - url: https://www.lutherancathedral.ru/
#      name: Lutheran_cathedral_BIG_842_pages
    - url: https://dombulgakova.ru/
      name: Дом_Булгакова_529_pages
#    - url: https://www.svetlovka.ru/
#      name: Светловка_231_pages
#    - url: http://cimus.biz/
#      name: cimus.biz_19_pages
#    - url: https://xakep.ru/
#      name: xakep_big
#    - url: https://www.baeldung.com/
#      name: baeldung


