# example values
server:
  port: 8080

#
#logging:
#  level:
#    root: "warn"
#    org.springframework.web: "debug"
#    org.hibernate: "error"


spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  output:
      ansi:
        enabled: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true
      useUnicode: true
      characterEncoding: utf-8
jsoup-setting:
  jsoup:
    userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0
    referrer: http://www:google.com
    timeout: 10000
    ignoreHttpErrors: true
    followRedirects: false

indexing-settings:
  sites:
#    - url: https://volochek.life/
#      name: Volochek
#    - url: https://www.playback.ru/
#      name: PlayBack.Ru
#    - url: https://www.twitter.com
#      name: Switter
#    - url: http://radiomv.ru/
#      name: Радио_MV
#    - url: https://ipfran.ru/
#      name: IP_fran
#    - url: https://dimonvideo.ru/
#      name: Димон_Видео
##    - url: www.bbc.com
##      name: BBC.com
#    - url: https://lenta.ru/
#      name: Lenta
#    - url: https://nikoartgallery.com/
#      name: Niko_Art_Gallery
    - url: https://et-cetera.ru/mobile/
      name: Et_Cetera_4_mobile
    - url: https://www.lutherancathedral.ru/
      name: Lutheran_cathedral
#    - url: https://dombulgakova.ru/
#      name: Дом_Булгакова
#    - url: http://www.artlebedev.ru/
#      name: ArtLebedev
#    - url: https://www.svetlovka.ru/
#      name: Светловка
    - url: http://cimus.biz/
      name: cimus.biz
#    - url: https://exotic-zoo.ru
#      name: EXOTIC Zoo



