# example values
server:
  port: 8088
  error:
      include-message: always


spring:
  datasource:
    username: root
    password: password
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 30
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  output:
      ansi:
        enabled: always

  jpa:
    properties:
      hibernate:
#        enable_lazy_load_no_trans: true
#        event:
#          merge:
#            entity_copy_observer: allow


    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true
      useUnicode: true
      characterEncoding: utf-8
      dialect: org.hibernate.dialect.MySQL8Dialect
jsoup-setting:
  jsoup:
    userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0
    referrer: http://www:google.com
    timeout: 5_000
    ignoreHttpErrors: true
    followRedirects: false

indexing-settings:
  sites:
#    >15000
#    - url: https://www.artlebedev.ru/
#      name: ArtLebedev
#    - url: https://lenta.ru/
#      name: Lenta
#    - url: https://volochek.life/
#      name: Volochek_very_big_string_apporx_3r_links
#    - url: https://www.playback.ru/
#      name: PlayBack.Ru
#    - url: http://radiomv.ru/
#      name: Радио MV 13
#      1024
#    - url: https://ipfran.ru/
#      name: ИПФ РАН
#    - url: www.bbc.com
#      name: BBC.com
#    - 91
    - url: https://nikoartgallery.com/
      name: Niko Art
#      52
    - url: https://et-cetera.ru/
      name: Et Cet-era
#      842
    - url: https://www.lutherancathedral.ru/
      name: Lutheran Cathedral
#      529
#    - url: https://dombulgakova.ru/
#      name: Дом Булгакова
#      231
#    - url: https://www.svetlovka.ru/
#      name: Svetlovka
#      19
    - url: https://www.tretyakovgallery.ru/
      name: Третьяковская галерея
    - url: http://kulinarya.ru/
      name: Кулинария.Ру
#    - url: https://www.film.ru/
#      name: Film.ru - Рецензии на фильмы
#    - url: https://www.metro.ru
#      name: Московское метро
#    over heap
#    - url: https://zanauku.mipt.ru/
#      name: Журнал "За науку"
#    - url: http://cimus.biz/
#      name: Cimus
#    - url: https://xakep.ru/
#      name: xakep
#    - url: https://niasvizh.by/
#      name: Несвиж
#    - url: https://habr.com/ru/
#      name: JAVA_Hub Habr



